### ISSUE TITLE
PvP 2.0 Error by Kit Create

### ISSUE THREAD

**Issue by MrBeefchop** [Lukas0610/PvP2.0#1]
Before it works... But when I added arrows then it the error comes everytime! I have restartet the server... Works not..
CraftBukkit 1.8.8
Plugin NEWEST

Error: http://pastebin.com/H9YZkmyz

**Comment by MrBeefchop** [comment]
And one question how can I select the Kit as user? With which command? And please add a /pvp help ! And a completly Command List!

**Comment by Lukas0610** [comment]
Was not your fault, if you add any enchantment, it should work; fix is coming soon.
And a help-command will be implemented too.
